language: python

python:
  - "2.7"
  
#sudo: required
#dist: trusty

services:
  - mysql
  
addons:
  apt:
    packages:
      - apache2
      - mysql-server
      - mysql-client-core
      - mysql-client
      - libmysqlclient-dev
      
install:
  - pip install .
#  - sudo python setup.py install

before_script:
  - bookworm config --force mysql

script:
  - cd tests && python test_mysql.py && python test_API.py
