language: python

python:
  - "2.7"
  
sudo: required
dist: trusty

services:
  - mysql
  
addons:
  apt:
    packages:
      - apache2
      - mysql-server-5.6
      - mysql-client-core-5.6
      - mysql-client-5.6      
      
install:
  - sudo pip install .
  - sudo python setup.py install

before_script:
  - bookworm config --force mysql

script:
  - cd tests && python test_mysql.py && python test_API.py
