language: python

python:
  - "3.6"

sudo: required
dist: trusty

services:
  - mysql
  
addons:
  apt:
    packages:
      - mysql-server-5.6
      - mysql-client-core-5.6
      - mysql-client-5.6

install:
  - pip install .

script:
  - cd tests && python test_mysql.py && python test_API.py
