language: python

python:
  - "2.7"
  
sudo: required
dist: trusty

services:
  - mysql
  
addons:
  apt:
    packages:
      - apache2
      - libmysqlclient-dev

install:
  - sudo pip install .

before_script:
  - bookworm config mysql

script:
  - cd tests && python test_mysql.py && python test_API.py
