language: python

python:
  - "2.7"
  
sudo: required
dist: trusty

services:
  - mysql
  
addons:
  apt:
    packages:
      - parallel
      - apache2
      - mysql-server-5.6
      - mysql-client-core-5.6
      - mysql-client-5.6

before_install:
  # necessary for the pip installation, unfortunately?
  - sudo chown travis /usr/lib/cgi-bin
  - sudo service apache2 restart
  
install:
  - sudo pip install .
  - pip install .
  #- sudo python setup.py install

before_script:
  - bookworm config --force mysql
  - which python
  - cat /etc/mysql/my.cnf
  - ls /etc/bookworm
  - cat /etc/bookworm/admin.cnf
  
script:
  - cd tests && python test_mysql.py && python test_API.py && python test_webserver.py
